package com.example.datalist.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF875300)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFFFDDB9)
val light_onPrimaryContainer = Color(0xFF2B1700)
val light_secondary = Color(0xFF715A41)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFFDDDBD)
val light_onSecondaryContainer = Color(0xFF281805)
val light_tertiary = Color(0xFF55633C)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFD8E9B7)
val light_onTertiaryContainer = Color(0xFF131F02)
val light_error = Color(0xFFBA1A1A)
val light_onError = Color(0xFFFFFFFF)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF1F1B16)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF1F1B16)
val light_surfaceVariant = Color(0xFFF1E0D0)
val light_onSurfaceVariant = Color(0xFF504539)
val light_outline = Color(0xFF827568)

val dark_primary = Color(0xFFFFB963)
val dark_onPrimary = Color(0xFF472A00)
val dark_primaryContainer = Color(0xFF663E00)
val dark_onPrimaryContainer = Color(0xFFFFDDB9)
val dark_secondary = Color(0xFFDFC1A2)
val dark_onSecondary = Color(0xFF3F2D17)
val dark_secondaryContainer = Color(0xFF58432B)
val dark_onSecondaryContainer = Color(0xFFFDDDBD)
val dark_tertiary = Color(0xFFBCCD9D)
val dark_onTertiary = Color(0xFF283412)
val dark_tertiaryContainer = Color(0xFF3E4b27)
val dark_onTertiaryContainer = Color(0xFFD8E9B7)
val dark_error = Color(0xFFFFB4AB)
val dark_onError = Color(0xFF690005)
val dark_errorContainer = Color(0xFF93000A)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF1F1B16)
val dark_onBackground = Color(0xFFEBE1D9)
val dark_surface = Color(0xFF1F1B16)
val dark_onSurface = Color(0xFFEBE1D9)
val dark_surfaceVariant = Color(0xFF504539)
val dark_onSurfaceVariant = Color(0xFFD4C4B5)
val dark_outline = Color(0xFF9D8E81)